### ISSUE TITLE
Error on python templates/v1/basic.py --name my_agent --dashboard

### ISSUE THREAD

**Issue by katharine-murphy** [fetchai/agents-tac#389]
**Description**
On running the Alternative Build and Run instructions here: https://github.com/fetchai/agents-aea/blob/develop/docs/tac.md#alternative-build-and-run---wip

at this step `python templates/v1/basic.py --name my_agent --dashboard`

The script errors with the following log:

```(agents-tac) bash-3.2$ python templates/v1/basic.py --name my_agent --dashboard
Traceback (most recent call last):
  File "templates/v1/basic.py", line 78, in <module>
    main()
  File "templates/v1/basic.py", line 69, in main
    dashboard=agent_dashboard, private_key_pem=args.private_key_pem)
TypeError: __init__() missing 1 required positional argument: 'expected_version_id'
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://github.com/fetchai/agents-aea/blob/develop/docs/tac.md#alternative-build-and-run---wip
2. Follow the instructions

**Desktop**
 - MAC OS Mojave

**Comment by katharine-murphy** [comment]
As of today, this command still errors, but the error message is different ```(agents-tac) bash-3.2$ python templates/v1/basic.py --name my_agent --dashboard
Traceback (most recent call last):
  File "templates/v1/basic.py", line 27, in <module>
    from tac.agents.participant.v1.base.strategy import RegisterAs, SearchFor
  File "/Users/katharinemurphy/.local/share/virtualenvs/agents-tac-YBffReos/lib/python3.7/site-packages/tac-0.1.6-py3.7.egg/tac/agents/participant/v1/base/strategy.py", line 29, in <module>
    from tac.agents.participant.v1.base.states import WorldState
  File "/Users/katharinemurphy/.local/share/virtualenvs/agents-tac-YBffReos/lib/python3.7/site-packages/tac-0.1.6-py3.7.egg/tac/agents/participant/v1/base/states.py", line 38, in <module>
    from tac.platform.game.base import Transaction
  File "/Users/katharinemurphy/.local/share/virtualenvs/agents-tac-YBffReos/lib/python3.7/site-packages/tac-0.1.6-py3.7.egg/tac/platform/game/base.py", line 37, in <module>
    from aea.protocols.tac.message import TACMessage
ModuleNotFoundError: No module named 'aea.protocols.tac'```
